apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ifcg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0005-tenant/tkrw-pr714-0075-0005-app/devfile-sample-ifcg@sha256:91faab634a0c6c1caba65a907ecbd6f8c5637ebd24c7876bcb52738461f5af05
        name: my-nodejs
        resources: {}
status: {}
